<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
        <RootNamespace>GrpcServer</RootNamespace>
    </PropertyGroup>

    <ItemGroup>
        <Protobuf Include="Protos\greet.proto" GrpcServices="Server"/>
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Google.Protobuf" Version="3.31.1" />
        <PackageReference Include="Grpc.AspNetCore" Version="2.57.0"/>
        <PackageReference Include="Grpc.Net.Client" Version="2.71.0" />
        <PackageReference Include="System.Configuration.ConfigurationManager" Version="10.0.0-preview.4.25258.110" />
        <PackageReference Include="Grpc.Tools" Version="2.72.0">
          <PrivateAssets>all</PrivateAssets>
          <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
    </ItemGroup>

    <ItemGroup>
      <Content Include="..\.dockerignore">
        <Link>.dockerignore</Link>
      </Content>
    </ItemGroup>

    <ItemGroup>
      <Content Remove="OldServer\App.config" />
    </ItemGroup>
    
    

</Project>
